### ISSUE TITLE
It will not start

### ISSUE THREAD

**Issue by Zelorous** [Lord-Zedd/H5Bitmap#1]
I don't know whether its my pc or just me, but I cant seem to get the script to start

**Comment by Lord-Zedd** [comment]
Do you have .net 4.5.2 installed?

**Comment by Zelorous** [comment]
No I do not... but I'm installing it now... thanks for the speedy reply

**Comment by Zelorous** [comment]
Yes, I do have it, or at least a newer version of it I think... It says something at the beginning about line 5 or 6... Ive tried running both the app and main window and nothing

**Comment by Lord-Zedd** [comment]
That is the source code. The compiled exe can be found under releases https://github.com/Lord-Zedd/H5Bitmap/releases

**Comment by Zelorous** [comment]
Thanks, now all I need to do is find something the decompile the .material files
